cp-kafka-env:
  &kafka-env
  CLUSTER_ID: vHCgQyIrRHG8Jv27qI2h3Q
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SSL,INTERNAL:SASL_SSL,EXTERNAL:SASL_SSL
  KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_PROCESS_ROLES: 'broker,controller'
  KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:19091

  # Logging
  KAFKA_LOG_RETENTION_HOURS: '1'
  KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
  KAFKA_LOG_SEGMENT_BYTES: 1073741824
  KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
  KAFKA_LOG4J_ROOT_LOGLEVEL: INFO # DEBUG

  # Authentication
  KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER # List of enabled SASL mechanisms
  KAFKA_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: ${KAFKA_IDP_TOKEN_ENDPOINT}
  KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: ${KAFKA_IDP_JWKS_ENDPOINT}
  KAFKA_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: ${KAFKA_EXPECTED_AUDIENCE}
  KAFKA_SASL_OAUTHBEARER_EXPECTED_ISSUER: ${KAFKA_IDP_EXPECTED_ISSUER}
  KAFKA_SASL_OAUTHBEARER_SUB_CLAIM_NAME: ${KAFKA_SUB_CLAIM_NAME}
  KAFKA_SASL_OAUTHBEARER_SCOPE_CLAIM_NAME: ${KAFKA_SCOPE_CLAIM_NAME}
  KAFKA_PRINCIPAL_BUILDER_CLASS: io.confluent.kafka.security.authenticator.OAuthKafkaPrincipalBuilder
  KAFKA_SASL_LOGIN_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
  KAFKA_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler
  KAFKA_SUPER_USERS: User:admin;User:${KAFKA_SUPERUSER_CLIENT_ID};User:${KAFKA_SSO_CLIENT_ID}
  KAFKA_BROKER_USERS: User:${KAFKA_SUPERUSER_CLIENT_ID}

  # Authorizer
  KAFKA_AUTHORIZER_CLASS_NAME: io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer
  KAFKA_CONFLUENT_AUTHORIZER_ACCESS_RULE_PROVIDERS: CONFLUENT,KRAFT_ACL

  # encryption
  KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2
  KAFKA_SSL_CLIENT_AUTH: 'required'
  KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 'https'
  KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
  KAFKA_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_SSL_KEY_PASSWORD: ${CERT_SECRET}
  KAFKA_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_SSL_KEYSTORE_FILENAME: keystore.p12
  KAFKA_SSL_KEYSTORE_CREDENTIALS: creds.txt
  KAFKA_SSL_KEY_CREDENTIALS: creds.txt
  KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
  KAFKA_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_SSL_TRUSTSTORE_FILENAME: truststore.p12
  KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds.txt
  KAFKA_SSL_CIPHER_SUITES: ${SSL_CIPHER_SUITES}

  # Internal Listener
  KAFKA_LISTENER_NAME_INTERNAL_SASL_ENABLED_MECHANISMS: OAUTHBEARER
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: ${KAFKA_IDP_TOKEN_ENDPOINT}
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: ${KAFKA_IDP_JWKS_ENDPOINT}
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: ${KAFKA_EXPECTED_AUDIENCE}
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_EXPECTED_ISSUER: ${KAFKA_IDP_EXPECTED_ISSUER}
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_SUB_CLAIM_NAME: ${KAFKA_SUB_CLAIM_NAME}
  KAFKA_LISTENER_NAME_INTERNAL_SASL_OAUTHBEARER_GROUPS_CLAIM_NAME: ${KAFKA_GROUP_CLAIM_NAME}
  KAFKA_LISTENER_NAME_INTERNAL_OAUTHBEARER_SASL_JAAS_CONFIG: |
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
        oauth.client.id="${KAFKA_SUPERUSER_CLIENT_ID}" \
        oauth.client.secret="${KAFKA_SUPERUSER_CLIENT_SECRET}" \
        oauth.token.endpoint.uri="${KAFKA_IDP_TOKEN_ENDPOINT}" \
        oauth.jwks.endpoint.uri="${KAFKA_IDP_JWKS_ENDPOINT}" \
        oauth.expected.audience="${KAFKA_EXPECTED_AUDIENCE}" \
        oauth.valid.issuer.uri="${KAFKA_IDP_EXPECTED_ISSUER}" \
        principalClaimName="${KAFKA_SUB_CLAIM_NAME}" \
        refresh_ms="3000" \
        oauth.ssl.endpoint.identification.algorithm="https" \
        oauth.ssl.keystore.type="PKCS12" \
        oauth.ssl.keystore.location="/etc/kafka/secrets/keystore.p12" \
        oauth.ssl.keystore.password="${CERT_SECRET}" \
        oauth.ssl.key.password="${CERT_SECRET}"  \
        oauth.ssl.truststore.type="PKCS12" \
        oauth.ssl.truststore.location="/etc/kafka/secrets/truststore.p12" \
        oauth.ssl.truststore.password="${CERT_SECRET}";
  KAFKA_LISTENER_NAME_INTERNAL_PRINCIPAL_BUILDER_CLASS: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
  KAFKA_LISTENER_NAME_INTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
  KAFKA_LISTENER_NAME_INTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler

  KAFKA_LISTENER_NAME_INTERNAL_SSL_CLIENT_AUTH: 'required'
  KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 'https'
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_INTERNAL_SSL_KEY_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
  KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_INTERNAL_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([a-zA-Z0-9]*).*$$/$$1/L,DEFAULT

  # Controller Listener
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_CLIENT_AUTH: 'required'
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 'https'
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_KEY_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
  KAFKA_LISTENER_NAME_CONTROLLER_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}

  # External listener
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: OAUTHBEARER
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: ${KAFKA_IDP_TOKEN_ENDPOINT}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: ${KAFKA_IDP_JWKS_ENDPOINT}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: ${KAFKA_EXPECTED_AUDIENCE}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_EXPECTED_ISSUER: ${KAFKA_IDP_EXPECTED_ISSUER}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_SUB_CLAIM_NAME: ${KAFKA_SUB_CLAIM_NAME}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_GROUPS_CLAIM_NAME: ${KAFKA_GROUP_CLAIM_NAME}
  KAFKA_LISTENER_NAME_EXTERNAL_SASL_OAUTHBEARER_REQUIRED_SCOPE: kafka
  KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_JAAS_CONFIG: |
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
        oauth.client.id="${KAFKA_SUPERUSER_CLIENT_ID}" \
        oauth.client.secret="${KAFKA_SUPERUSER_CLIENT_SECRET}" \
        oauth.token.endpoint.uri="${KAFKA_IDP_TOKEN_ENDPOINT}" \
        oauth.jwks.endpoint.uri="${KAFKA_IDP_JWKS_ENDPOINT}" \
        oauth.expected.audience="${KAFKA_EXPECTED_AUDIENCE}" \
        oauth.valid.issuer.uri="${KAFKA_IDP_EXPECTED_ISSUER}" \
        principalClaimName="${KAFKA_SUB_CLAIM_NAME}" \
        refresh_ms="3000" \
        oauth.ssl.endpoint.identification.algorithm="https" \
        oauth.ssl.keystore.type="PKCS12" \
        oauth.ssl.keystore.location="/etc/kafka/secrets/keystore.p12" \
        oauth.ssl.keystore.password="${CERT_SECRET}" \
        oauth.ssl.key.password="${CERT_SECRET}"  \
        oauth.ssl.truststore.type="PKCS12" \
        oauth.ssl.truststore.location="/etc/kafka/secrets/truststore.p12" \
        oauth.ssl.truststore.password="${CERT_SECRET}";
  KAFKA_LISTENER_NAME_EXTERNAL_PRINCIPAL_BUILDER_CLASS: io.confluent.kafka.security.authenticator.OAuthKafkaPrincipalBuilder
  KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_LOGIN_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
  KAFKA_LISTENER_NAME_EXTERNAL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.confluent.kafka.server.plugins.auth.token.CompositeBearerValidatorCallbackHandler

  KAFKA_LISTENER_NAME_EXTERNAL_SSL_CLIENT_AUTH: 'required'
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: 'https'
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEYSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/keystore.p12
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_KEY_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_TRUSTSTORE_TYPE: PKCS12
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/truststore.p12
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}
  KAFKA_LISTENER_NAME_EXTERNAL_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([a-zA-Z0-9]*).*$$/$$1/L,DEFAULT

  # metrics reporter
  #  KAFKA_JMX_PORT: 9101
  #  KAFKA_JMX_HOSTNAME: localhost
  #  KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka1 -Dcom.sun.management.jmxremote.rmi.port=9101

  # Others
  KAFKA_AUTO_CREATE_TOPICS_ENABLED: 'true'
  KAFKA_DELETE_TOPIC_ENABLED: 'true'
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 300000    # 5 mins
  KAFKA_DEFAULT_REPLICATION_FACTOR: 1           # 1 brokers
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1        # Đảm bảo có quorum (n - 1) brokers sẵn sàng
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  KAFKA_MIN_INSYNC_REPLICAS: 2                  # Nên >= 2 khi replication = 3 (tối thiểu 2 replicas sống)
  KAFKA_REPLICA_LAG_TIME_MAX_MS: 30000          # 30s là hợp lý cho phát hiện lag

  KAFKA_NUM_IO_THREADS: 4                       # Tùy thuộc CPU (thường = số vCPU)
  KAFKA_NUM_NETWORK_THREADS: 1                  # Một cho mỗi broker là đủ (hoặc = số NIC)
  KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 2    # Nếu bạn dùng 1 ổ đĩa: để = 2 giúp phục hồi nhanh hơn

  KAFKA_OFFSETS_COMMIT_TIMEOUT_MS: 10000        # 10s
  KAFKA_OFFSETS_RETENTION_MINUTES: 10080        # 7 days
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_OFFSETS_TOPIC_COMPRESSION_CODEC: 1      # gzip

  #  EXTRA_ARGS: "-javaagent:/usr/bin/jmx/jmx_prometheus_javaagent.jar=1234:/usr/bin/jmx/exporter.yml"
  KAFKA_OPTS: |
    -Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=${KAFKA_IDP_JWKS_ENDPOINT},${KAFKA_IDP_TOKEN_ENDPOINT},${IDP_AUTH_ENDPOINT},${IDP_DEVICE_AUTH_ENDPOINT}
  KAFKA_HEAP_OPTS: "-Xms${BROKER_HEAP} -Xmx${BROKER_HEAP}"

cp-schema-registry-env:
  &schema-registry-env
  SCHEMA_REGISTRY_GROUP_ID: "schema-registry-group"
  SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
  SCHEMA_REGISTRY_LISTENERS: https://0.0.0.0:8081
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:39091

  SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO

  # Encryption
  SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: 'https'
  SCHEMA_REGISTRY_SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL: 'https'
  SCHEMA_REGISTRY_SSL_CLIENT_AUTHENTICATION: 'REQUIRED'
  SCHEMA_REGISTRY_SSL_KEYSTORE_TYPE: PKCS12
  SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION: /etc/schema-registry/secrets/keystore.p12
  SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  SCHEMA_REGISTRY_SSL_KEY_PASSWORD: ${CERT_SECRET}
  SCHEMA_REGISTRY_SSL_TRUSTSTORE_TYPE: PKCS12
  SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION: /etc/schema-registry/secrets/truststore.p12
  SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}
  SCHEMA_REGISTRY_SSL_CIPHER_SUITES: ${SSL_CIPHER_SUITES}

  # Schema store
  SCHEMA_REGISTRY_KAFKASTORE_TIMEOUT_MS: 10000
  SCHEMA_REGISTRY_KAFKASTORE_INIT_TIMEOUT_MS: 120000
  SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
  SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: OAUTHBEARER
  SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: |
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
        oauth.client.id="${SR_CLIENT_ID}" \
        oauth.client.secret="${SR_CLIENT_SECRET}" \
        oauth.token.endpoint.uri="${KAFKA_IDP_TOKEN_ENDPOINT}" \
        principalClaimName="${KAFKA_SUB_CLAIM_NAME}" \
        refresh_ms="3000" \
        oauth.ssl.truststore.type="PKCS12" \
        oauth.ssl.truststore.location="/etc/schema-registry/secrets/truststore.p12" \
        oauth.ssl.truststore.password="${CERT_SECRET}";
  SCHEMA_REGISTRY_KAFKASTORE_PRINCIPAL_BUILDER_CLASS: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
  SCHEMA_REGISTRY_KAFKASTORE_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
  SCHEMA_REGISTRY_KAFKASTORE_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
  SCHEMA_REGISTRY_KAFKASTORE_UPDATE_HANDLERS: io.confluent.schema.exporter.storage.SchemaExporterUpdateHandler

  SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_TYPE: PKCS12
  SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/schema-registry/secrets/keystore.p12
  SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: ${CERT_SECRET}
  SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: ${CERT_SECRET}
  SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_TYPE: PKCS12
  SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/schema-registry/secrets/truststore.p12
  SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: ${CERT_SECRET}

  SCHEMA_REGISTRY_SASL_MECHANISM: OAUTHBEARER
  SCHEMA_REGISTRY_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: ${KAFKA_IDP_TOKEN_ENDPOINT}
  SCHEMA_REGISTRY_OAUTHBEARER_JWKS_ENDPOINT_URL: ${KAFKA_IDP_JWKS_ENDPOINT}
  SCHEMA_REGISTRY_OAUTHBEARER_EXPECTED_ISSUER: ${KAFKA_IDP_EXPECTED_ISSUER}
  SCHEMA_REGISTRY_OAUTHBEARER_EXPECTED_AUDIENCE: ${KAFKA_EXPECTED_AUDIENCE}
  SCHEMA_REGISTRY_OAUTHBEARER_SUB_CLAIM_NAME: ${KAFKA_SUB_CLAIM_NAME}
  SCHEMA_REGISTRY_OAUTHBEARER_GROUPS_CLAIM_NAME: ${KAFKA_GROUP_CLAIM_NAME}
  SCHEMA_REGISTRY_SASL_JAAS_CONFIG: |
    org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
        oauth.client.id="${SR_CLIENT_ID}" \
        oauth.client.secret="${SR_CLIENT_SECRET}" \
        oauth.token.endpoint.uri="${KAFKA_IDP_TOKEN_ENDPOINT}" \
        principalClaimName="${KAFKA_SUB_CLAIM_NAME}" \
        refresh_ms="3000" \
        ssl.truststore.type="PKCS12" \
        ssl.truststore.location="/etc/schema-registry/secrets/truststore.p12" \
        ssl.truststore.password="${CERT_SECRET}";
  SCHEMA_REGISTRY_PRINCIPAL_BUILDER_CLASS: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
  SCHEMA_REGISTRY_SASL_LOGIN_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
  SCHEMA_REGISTRY_SASL_SERVER_CALLBACK_HANDLER_CLASS: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler

  #  SCHEMA_REGISTRY_REST_AUTH_JMX_ENABLED: 'true'
  #  EXTRA_ARGS: "-javaagent:/usr/bin/jmx/jmx_prometheus_javaagent.jar=1234:/usr/bin/jmx/exporter.yml"
  SCHEMA_REGISTRY_LEADER_ELIGIBILITY: 'true'
  SCHEMA_REGISTRY_MODE_MUTABILITY: 'true'
  SCHEMA_REGISTRY_DEBUG: 'true'
  KAFKA_HEAP_OPTS: "-Xms${SCHEMA_HEAP} -Xmx${SCHEMA_HEAP}"