services:
  # --------- Postgres ---------
  postgres:
#    build:
#      args:
#        POSTGRES_TAG: ${POSTGRES_TAG:-latest}
#      context: ../postgresql
    image: ${NAMESPACE}/${REPOSITORY_NAME}/postgres:${POSTGRES_TAG:-latest}
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    command: >
      postgres
      -c max_connections=500
      -c config_file=/etc/postgres/postgres.conf
      -c hba_file=/etc/postgres/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    volumes:
      - ../postgres/config/postgres.conf:/etc/postgres/postgres.conf:ro
      - ../postgres/config/pg_hba.conf:/etc/postgres/pg_hba.conf:ro
      - ../postgres/init-db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_TEXT_PASSWORD} # Use secret instead
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password # Reference to the secret
      PGDATA: /var/lib/postgresql/18/docker
    env_file: ../.env

  # --------- Keycloak ---------
  keycloak:
    image: ${NAMESPACE}/${REPOSITORY_NAME}/keycloak:${KEYCLOAK_TAG:-latest}
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080" # HTTP
      - "9990:9990" # Management port
    networks:
      - my-network
    command: [
      "start",
      "--import-realm",
      "--optimized",
      "--verbose",
    ]
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9990; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9990\r\nConnection: close\r\n\r\n' >&3; cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: always # unless-stopped
    volumes:
      - ../keycloak/import:/opt/keycloak/data/import
      - ../keycloak/export:/opt/keycloak/data/export
    environment:
      # --- Keycloak Configuration ---
      KC_HTTP_MANAGEMENT_PORT: 9990
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      # --- HTTP & Host Configuratiown ---
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
      # --- Database Configuration ---
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?sslmode=verify-full&sslrootcert=/opt/keycloak/conf/root.crt&sslcert=/opt/keycloak/conf/server.crt&sslkey=/opt/keycloak/conf/server.pk8
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_TEXT_PASSWORD}
    env_file: ../.env

secrets:
  postgres_password:
    file: ../secrets/postgres/postgres.password

volumes:
  pgdata:
    driver: local
#  kafka0-data:
#    driver: local

networks:
  my-network:
    driver: bridge