services:
  # --------- Postgres ---------
  postgres:
    build:
      args:
        POSTGRES_TAG: ${POSTGRES_TAG:-latest}
      context: ./postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    command: >
      postgres 
      -c 'max_connections=500'
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/18/main/server.crt
      -c ssl_key_file=/var/lib/postgresql/18/main/server.key
      -c ssl_ca_file=/var/lib/postgresql/18/main/ca.crt
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres" ]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    restart: always # unless-stopped
    volumes:
      - ./postgres/init-db:/docker-entrypoint-initdb.d:ro
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  # --------- Keycloak ---------
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG:-latest}
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080" # HTTP
      - "9990:9990" # Management port
    networks:
      - my-network
    command: [
      "start",
      "--health-enabled=true",
      "--import-realm"
    ]
    restart: always # unless-stopped
    volumes:
      - ./keycloak/realms.dev.json:/opt/keycloak/data/import/realms.dev.json
      - ./keycloak/exports:/opt/keycloak/data/export
    environment:
      KC_HTTP_MANAGEMENT_PORT: 9990
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_PROXY: edge
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realms.dev.json
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  mongodb-data:
    driver: local
  postgres-data:
    driver: local
  kafka1-data:
    driver: local

networks:
  my-network:
    driver: bridge