services:
  # --------- Postgres ---------
  postgres:
#    build:
#      args:
#        POSTGRES_TAG: ${POSTGRES_TAG:-latest}
#      context: ../postgresql
    image: ldnhan/postgres:${POSTGRES_TAG:-latest}
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - my-network
    command: >
      postgres
      -c max_connections=500
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    volumes:
      - ../postgresql/config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ../postgresql/config/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ../postgresql/init-db:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/18/docker
    env_file: ../.env
    secrets:
      - postgres_password

  # --------- Keycloak ---------
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_TAG:-latest}
    container_name: keycloak
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080" # HTTP
      - "9990:9990" # Management port
    networks:
      - my-network
    command: [
      "start",
      "--health-enabled=true",
      "--import-realm"
    ]
    restart: always # unless-stopped
    volumes:
      - ./keycloak/realms.cp.json:/opt/keycloak/data/import/realms.dev.json
      - ./secrets/certs/ca/ca.crt:/etc/ssl/certs/root.crt:ro
      - ./keycloak/exports:/opt/keycloak/data/export
    environment:
      KC_HTTP_MANAGEMENT_PORT: 9990
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_PROXY: edge
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realms.dev.json
      KC_DB: postgres
      #      KC_DB_URL_HOST: postgres
      #      KC_DB_URL_PORT: 5432
      #      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?sslmode=verify-full&sslrootcert=/etc/ssl/certs/root.crt
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

secrets:
  postgres_password:
    file: ../secrets/postgresql/postgresql.password

volumes:
  pgdata:
    driver: local
#  kafka1-data:
#    driver: local

networks:
  my-network:
    driver: bridge